"","rowname","error"
"1","ErrorMessage"," 'envir' 引数が不正です "
"2","ErrorType","error"
"3","ErrorMessage6"," 使われていない引数 (alist(x = )) "
"4","ErrorMessage7"," 引数 ""names"" がありませんし、省略時既定値もありません "
"5","ErrorMessage8","the condition has length > 1"
"6","ErrorMessage10"," 'allow_' の値が不正です "
"7","ErrorMessage18"," 'names' は文字ベクトルでなければなりません "
"8","ErrorMessage23"," 引数 ""sym"" がありませんし、省略時既定値もありません "
"9","ErrorMessage24"," 引数 ""fun"" がありませんし、省略時既定値もありません "
"10","ErrorMessage25"," 引数 ""env"" がありませんし、省略時既定値もありません "
"11","ErrorMessage26"," シンボルではありません "
"12","ErrorMessage30"," 関数でありません "
"13","ErrorMessage31"," '...' が不適切な文脈で使われました "
"14","ErrorMessage32"," 引数 ""f"" がありませんし、省略時既定値もありません "
"15","ErrorMessage33"," 変数 'x' （モード 'function'）は見つかりません "
"16","ErrorMessage35"," 引数 ""FUN"" がありませんし、省略時既定値もありません "
"17","ErrorMessage44","argument 'MoreArgs' of 'mapply' is not a list or pairlist"
"18","ErrorMessage57"," 使われていない引数 (alist(FUN = )) "
"19","ErrorMessage58"," 引数 ""x"" がありませんし、省略時既定値もありません "
"20","ErrorMessage59"," 負の添字と混在できるのは 0 という添字だけです "
"21","ErrorMessage60"," 単項演算子に対する引数が不正です "
"22","ErrorMessage61"," 'x' は名前付きの次元名を持たなければなりません "
"23","ErrorMessage62"," 'x' は配列ではありません "
"24","ErrorMessage64"," 使われていない引数 (alist(FUN = , quietly = )) "
"25","ErrorMessage71"," 使われていない引数 (alist(nrow = , ncol = )) "
"26","ErrorMessage72"," 引数 ""nc"" がありませんし、省略時既定値もありません "
"27","ErrorMessage76"," 'nrow' の値が不正です (負の値です) "
"28","ErrorMessage77"," 行列の大きさが数値ではありません "
"29","ErrorMessage80"," 引数 ""table"" がありませんし、省略時既定値もありません "
"30","ErrorMessage81","'list' object cannot be coerced to type 'double'"
"31","ErrorMessage82"," 強制変換により NA が生成されました "
"32","ErrorType82","warning"
"33","ErrorMessage88"," 引数 ""arg"" がありませんし、省略時既定値もありません "
"34","ErrorMessage89"," 'arg' は、NULL かひとつの文字ベクトルでなければなりません "
"35","ErrorMessage97"," 引数の型が不正です "
"36","ErrorMessage98"," 使われていない引数 (alist(substitute = )) "
"37","ErrorMessage99"," 'definition' 引数が不正です "
"38","ErrorMessage100"," 'call' 引数が不正です "
"39","ErrorMessage115"," 引数が論理変数として解釈することができません "
"40","ErrorMessage119"," オブジェクト '.Generic' がありません "
"41","ErrorMessage120","non-numeric-alike variable(s) in data frame: rowname, ."
"42","ErrorMessage121","non-numeric-alike variable(s) in data frame: 1"
"43","ErrorMessage144"," 'byrow' 引数が不正です "
"44","ErrorMessage153"," 引数 1 が空です "
"45","ErrorMessage154"," max の引数に有限な値がありません: -Inf を返します "
"46","ErrorMessage159","'arg' should be one of “random”, “first”, “last”"
"47","ErrorMessage164"," 引数は数値でも論理値でもありません。NA 値を返します "
"48","ErrorMessage171"," 'trim' は長さ 1 の数値でなければなりません "
"49","ErrorMessage186"," 'origin' を指定しなければなりません "
"50","ErrorMessage187"," 'x' からクラス “POSIXct” へ変換は定義されていません "
"51","ErrorMessage188"," 文字列は標準的な曖昧さのない書式にはなっていません "
"52","ErrorMessage191"," 引数 ""from"" がありませんし、省略時既定値もありません "
"53","ErrorMessage192"," 'from' は raw または文字でなければなりません "
"54","ErrorMessage197","'arg' should be one of “gzip”, “bzip2”, “xz”, “none”"
"55","ErrorMessage200","'from' must be raw or character"
"56","ErrorMessage206","'arg' should be one of “unknown”, “gzip”, “bzip2”, “xz”, “none”"
"57","ErrorMessage209"," 使われていない引数 (x) "
"58","ErrorMessage210"," 使われていない引数 (df) "
"59","ErrorMessage211"," 使われていない引数 (""df"") "
"60","ErrorMessage214"," 引数 ""y"" がありませんし、省略時既定値もありません "
"61","ErrorMessage218"," 'by' は列数にマッチしなければなりません "
"62","ErrorMessage236"," 引数 ""..1"" がありませんし、省略時既定値もありません "
"63","ErrorMessage237","
"
"64","ErrorType237","message"
"65","ErrorMessage244"," 一番目の引数が不正です "
"66","ErrorMessage260"," 二番目の引数は環境でなければなりません "
"67","ErrorMessage263"," min の引数に有限な値がありません: Inf を返します "
"68","ErrorMessage265"," 'missing' は引数に対してだけ使えます "
"69","ErrorMessage267"," 関数の引数が数値ではありません "
"70","ErrorMessage269"," 引数 2 が空です "
"71","ErrorMessage270"," 2 個の引数が 'Mod' に渡されましたが、1 が必要とされています "
"72","ErrorMessage278"," 引数 ""value"" がありませんし、省略時既定値もありません "
"73","ErrorMessage284"," 変数 'as.df' （モード 'function'）は見つかりません "
"74","ErrorMessage287"," 'months' をクラス ""name"" のオブジェクトに適用できるようなメソッドがありません "
"75","ErrorMessage288"," 'months' をクラス ""data.frame"" のオブジェクトに適用できるようなメソッドがありません "
"76","ErrorMessage289"," 'months' をクラス ""character"" のオブジェクトに適用できるようなメソッドがありません "
"77","ErrorMessage291"," 'trim' 引数が不正です "
"78","ErrorMessage293","'list' object cannot be coerced to type 'logical'"
"79","ErrorMessage311","$ operator is invalid for atomic vectors"
"80","ErrorMessage314"," 1 個の引数が 'names<-' に渡されましたが、2 が必要とされています "
"81","ErrorMessage318"," 使われていない引数 (alist(xx = , tz = , cl = )) "
"82","ErrorMessage319"," 使われていない引数 (alist(xx = x, tz = , cl = )) "
"83","ErrorMessage320"," 使われていない引数 (alist(xx = x, tz = x, cl = )) "
"84","ErrorMessage321"," 使われていない引数 (alist(xx = x, tz = df, cl = )) "
"85","ErrorMessage322"," 使われていない引数 (alist(xx = x, tz = ""df"", cl = )) "
"86","ErrorMessage323"," 使われていない引数 (alist(xx = df, tz = ""df"", cl = )) "
"87","ErrorMessage324"," 使われていない引数 (alist(xx = ""df"", tz = ""df"", cl = )) "
"88","ErrorMessage325"," 使われていない引数 (xx = ""df"", tz = ""df"", cl = x) "
"89","ErrorMessage326"," 使われていない引数 (xx = ""df"", tz = ""df"", cl = df) "
"90","ErrorMessage327"," 使われていない引数 (xx = ""df"", tz = ""df"", cl = ""df"") "
"91","ErrorMessage332"," NULL に対して属性を設定しようとしました "
"92","ErrorMessage334"," 使われていない引数 (alist(exports = )) "
"93","ErrorMessage335"," 引数 ""ns"" がありませんし、省略時既定値もありません "
"94","ErrorMessage336"," 環境ではありません "
"95","ErrorMessage342"," 使われていない引数 (alist(self = )) "
"96","ErrorMessage343"," 引数がありませんし、省略時既定値もありません "
"97","ErrorMessage344"," 使われていない引数 (alist(classes = )) "
"98","ErrorMessage345"," 引数 ""vars"" がありませんし、省略時既定値もありません "
"99","ErrorMessage348"," 'The name of the object (e.g,. a class or generic function) to find in the meta-data' は単一の文字列でなければなりません (クラス ""numeric"" のオブジェクトでした) "
"100","ErrorMessage352"," 'The name of the object (e.g,. a class or generic function) to find in the meta-data' は単一の文字列でなければなりません(長さ 4699 の文字ベクトルでした) "
"101","ErrorMessage353"," 名前空間ではありません "
"102","ErrorMessage355"," ‘df’ という名前のパッケージはありません "
"103","ErrorMessage358"," 使われていない引数 (alist(imports = )) "
"104","ErrorMessage359"," 引数 ""self"" がありませんし、省略時既定値もありません "
"105","ErrorMessage371"," ‘x’ という名前のパッケージはありません "
"106","ErrorMessage372"," 使われていない引数 (alist(methods = )) "
"107","ErrorMessage375"," 'pos' 引数が不正です "
"108","ErrorMessage382"," 検索リストに ""ErrorMessage"" という項目はありません "
"109","ErrorMessage383"," 検索リストに ""df"" という項目はありません "
"110","ErrorMessage386"," 1 個の引数が 'nargs' に渡されましたが、0 が必要とされています "
"111","ErrorMessage391"," 'type' 引数が不正です "
"112","ErrorMessage403"," 'enclos' は環境でなくてはなりません "
"113","ErrorMessage411"," break/next に対応するループがないので、トップレベルにジャンプします "
"114","ErrorMessage414"," 'function' は関数ではなく、単に 8 型です "
"115","ErrorMessage421"," 使われていない引数 (alist(msgid = , msgid_plural = )) "
"116","ErrorMessage422"," 引数 ""n"" がありませんし、省略時既定値もありません "
"117","ErrorMessage423"," 引数 ""msg1"" がありませんし、省略時既定値もありません "
"118","ErrorMessage424"," 引数 ""msg2"" がありませんし、省略時既定値もありません "
"119","ErrorMessage425"," 'n' 引数が不正です "
"120","ErrorMessage437"," 引数 ""obj"" がありませんし、省略時既定値もありません "
"121","ErrorMessage445"," 'A' は数値行列でなければなりません "
"122","ErrorMessage451"," 引数 ""path"" がありませんし、省略時既定値もありません "
"123","ErrorMessage452"," 'path' 引数が不正です "
"124","ErrorMessage462"," 'length' 引数が不正です "
"125","ErrorMessage467"," 無効なバージョンの指定 ‘-1’, ‘-Inf’, ‘NaN’, ‘Inf’ です "
"126","ErrorMessage468","'length(x) = 6 > 1' in coercion to 'logical(1)'"
"127","ErrorMessage469"," 'x 'y' y' の && の型が不正です "
"128","ErrorMessage481","NAs introduced by coercion to integer range"
"129","ErrorMessage498"," 0 個の引数が 'oldClass<-' に渡されましたが、2 が必要とされています "
"130","ErrorMessage499"," 1 個の引数が 'oldClass<-' に渡されましたが、2 が必要とされています "
"131","ErrorMessage502"," ファイル名引数が不正です "
"132","ErrorMessage504","‘df’ is not a directory"
"133","ErrorMessage505"," 'lifo' 引数が不正です "
"134","ErrorMessage507"," 'add' 引数が不正です "
"135","ErrorMessage511"," 使われていない引数 (alist(warn = )) "
"136","ErrorMessage512"," 'open' をクラス ""name"" のオブジェクトに適用できるようなメソッドがありません "
"137","ErrorMessage514"," 'open' をクラス ""c('double', 'numeric')"" のオブジェクトに適用できるようなメソッドがありません "
"138","ErrorMessage515"," 'open' をクラス ""data.frame"" のオブジェクトに適用できるようなメソッドがありません "
"139","ErrorMessage516"," 'open' をクラス ""character"" のオブジェクトに適用できるようなメソッドがありません "
"140","ErrorMessage517"," 引数 ""con"" がありませんし、省略時既定値もありません "
"141","ErrorMessage519"," 'con' はコネクションではありません "
"142","ErrorMessage543"," 'open' をクラス ""NULL"" のオブジェクトに適用できるようなメソッドがありません "
"143","ErrorMessage551"," 'text' 引数が不正です "
"144","ErrorMessage553"," オブジェクト '.Method' がありません "
"145","ErrorMessage619","'arg' should be one of “auto”, “shell”, “radix”"
"146","ErrorMessage622","cannot xtfrm data frames"
"147","ErrorMessage624"," 引数 ""X"" がありませんし、省略時既定値もありません "
"148","ErrorMessage625"," 引数 ""Y"" がありませんし、省略時既定値もありません "
"149","ErrorMessage627"," 引数 ""df2"" がありませんし、省略時既定値もありません "
"150","ErrorMessage635"," 無効なバージョンの指定 ‘-1’, ‘0’, ‘1’, ‘-Inf’, ‘NaN’, ‘Inf’ です "
"151","ErrorMessage641"," 使われていない引数 (alist(lib.loc = )) "
"152","ErrorMessage642"," 引数 ""pkgname"" がありませんし、省略時既定値もありません "
"153","ErrorMessage643"," 文字列でない引数です "
"154","ErrorMessage646","'arg' should be one of “onLoad”, “attach”, “detach”, “onUnload”"
"155","ErrorMessage649"," 使われていない引数 (alist(pkg = , lib.loc = )) "
"156","ErrorMessage650"," 引数 ""package.lib"" がありませんし、省略時既定値もありません "
"157","ErrorMessage652"," 使われていない引数 (alist(pkg = )) "
"158","ErrorMessage653"," 引数 ""package"" がありませんし、省略時既定値もありません "
"159","ErrorMessage654"," 引数 ""lib.loc"" がありませんし、省略時既定値もありません "
"160","ErrorMessage665"," 引数 'ｘ' は raw, 整数もしくは論理型でなくてはなりません "
"161","ErrorMessage668","'arg' should be one of “raw”, “integer”, “double”"
"162","ErrorMessage674"," 使われていない引数 (alist(envir = )) "
"163","ErrorMessage676"," 引数が環境ではありません "
"164","ErrorMessage679"," 使われていない引数 (envir = x) "
"165","ErrorMessage680"," 使われていない引数 (envir = df) "
"166","ErrorMessage681"," 使われていない引数 (envir = ""df"") "
"167","ErrorMessage683"," 使われていない引数 (alist(envir = , value = )) "
"168","ErrorMessage693"," 'n' の値が不正です "
"169","ErrorMessage696"," 'file' は文字列またはコネクションでなければなりません "
"170","ErrorMessage698"," 'encoding' の値が不正です "
"171","ErrorMessage700"," 引数 'encoding= ""df""' は無視されます "
"172","ErrorMessage712"," 使われていない引数 (alist(file = , env = )) "
"173","ErrorMessage719"," パッケージ ‘df’ には 'NAMESPACE' ファイルがありません "
"174","ErrorMessage724"," 区切り文字が不正です "
"175","ErrorMessage730"," 'collapse' 引数が不正です "
"176","ErrorMessage738"," 使われていない引数 (alist(verbose = , lib.loc = )) "
"177","ErrorMessage739"," どのパッケージもロードされません "
"178","ErrorMessage748"," 使われていない引数 (alist(command = , text = )) "
"179","ErrorMessage749"," 引数 ""description"" がありませんし、省略時既定値もありません "
"180","ErrorMessage750"," 'description' 引数が不正です "
"181","ErrorMessage755"," pipe() コマンド 'df' を開くことができません: Invalid argument "
"182","ErrorMessage756"," 'encoding' 引数が不正です "
"183","ErrorMessage760"," 'x' と 'y' の長さが異なります "
"184","ErrorMessage777"," 引数がありません "
"185","ErrorMessage784"," 'na.rm' の値が不正です "
"186","ErrorMessage797"," 多項式の係数が不正です "
"187","ErrorMessage798"," 引数 ""z"" がありませんし、省略時既定値もありません "
"188","ErrorMessage799"," 型 'list'（'polyroot' における）は未実装です 
"
"189","ErrorMessage800"," 型 'character'（'polyroot' における）は未実装です 
"
"190","ErrorMessage804","'list' object cannot be coerced to type 'integer'"
"191","ErrorMessage847"," 'decimal.mark' 引数が不正です "
"192","ErrorMessage858"," 値の長さは 1 でなければなりません、 
 しかし、FUN(X[[1]]) の結果の長さが 4699 です "
"193","ErrorMessage864"," オブジェクトが指定されていません "
"194","ErrorMessage868"," 引数 1 (タイプ 'list') は 'cat' で取り扱えません "
"195","ErrorMessage871"," 'conditionMessage' をクラス ""c('double', 'numeric')"" のオブジェクトに適用できるようなメソッドがありません "
"196","ErrorMessage872"," 'conditionMessage' をクラス ""data.frame"" のオブジェクトに適用できるようなメソッドがありません "
"197","ErrorMessage873"," 'conditionMessage' をクラス ""character"" のオブジェクトに適用できるようなメソッドがありません "
"198","ErrorMessage884","invalid 'max' / getOption(""max.print""): df"
"199","ErrorMessage888","invalid printing digits -1"
"200","ErrorMessage917","invalid printing digits -2147483648"
"201","ErrorMessage927"," 未定義の列が選ばれました "
"202","ErrorMessage929"," 添え字が許される範囲外です "
"203","ErrorMessage939","factor levels must be ""character"""
"204","ErrorMessage940"," 'quote' の値が不正です "
"205","ErrorMessage947"," 'quote' 引数が不正です "
"206","ErrorMessage953"," 'useSource' 引数が不正です "
"207","ErrorMessage961"," 文字オブジェクトしか書き込めません "
"208","ErrorMessage971"," 'right' 引数が不正です "
"209","ErrorMessage1025"," 'sep' の指定が不正です "
"210","ErrorMessage1036","invalid 'digits' parameter, allowed 1...22"
"211","ErrorMessage1050"," 'na.print' の指定が不正です "
"212","ErrorMessage1051"," 行ラベルが不正です "
"213","ErrorMessage1054"," 1 個の引数が 'proc.time' に渡されましたが、0 が必要とされています "
"214","ErrorMessage1059"," 引数 'type' (character) が不正です "
"215","ErrorMessage1068","'x' must have named dimnames"
"216","ErrorMessage1086"," 使われていない引数 (alist(value = )) "
"217","ErrorMessage1088"," 'dimnames' が配列以外に適用されました "
"218","ErrorMessage1100"," 計算結果が NaN になりました "
"219","ErrorMessage1101"," deriv = 2147483647 > 100 (= n_max) "
"220","ErrorMessage1102"," 数学関数に数値でない引数が渡されました "
"221","ErrorMessage1106"," 使われていない引数 (alist(x = , value = )) "
"222","ErrorMessage1107"," 引数 ""data"" がありませんし、省略時既定値もありません "
"223","ErrorMessage1108"," 引数 ""connection"" がありませんし、省略時既定値もありません "
"224","ErrorMessage1109"," 'data' 引数が不正です "
"225","ErrorMessage1113","'arg' should be one of “bytes”, “UTF-8”"
"226","ErrorMessage1127"," コネクションが不正です "
"227","ErrorMessage1131"," ""yes"", ""no"", ""ask"" または ""default"" のどれかが期待されています "
"228","ErrorMessage1138"," 'save' の値が認識できません "
"229","ErrorMessage1141"," 外部関数の呼び出し (引数 1) 中に NA/NaN/Inf があります "
"230","ErrorMessage1144"," 引数 ""qr"" がありませんし、省略時既定値もありません "
"231","ErrorMessage1145"," 最初の引数は QR 分解でなければなりません "
"232","ErrorMessage1164"," 引数は QR 分解ではありません "
"233","ErrorMessage1213"," 使われていない引数 (alist(qr = , y = )) "
"234","ErrorMessage1214"," 引数 ""a"" がありませんし、省略時既定値もありません "
